# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestPorsche():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_porsche(self):
    # Test name: porsche
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.copart.com/")
    # 2 | setWindowSize | 1787x1092 |  | 
    self.driver.set_window_size(1787, 1092)
    # 3 | runScript | window.scrollTo(0,1) |  | 
    self.driver.execute_script("window.scrollTo(0,1)")
    # 4 | mouseDownAt | id=input-search | 49.515625,22 | 
    element = self.driver.find_element(By.ID, "input-search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 5 | mouseMoveAt | id=input-search | 49.515625,22 | 
    element = self.driver.find_element(By.ID, "input-search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseUpAt | id=input-search | 49.515625,22 | 
    element = self.driver.find_element(By.ID, "input-search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 7 | click | id=input-search |  | 
    self.driver.find_element(By.ID, "input-search").click()
    # 8 | type | id=input-search | exotics | 
    self.driver.find_element(By.ID, "input-search").send_keys("exotics")
    # 9 | click | css=.btn-lightblue:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lightblue:nth-child(1)").click()
    # 10 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 11 | waitForElementPresent | id=serverSideDataTable | 30000 | 
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "serverSideDataTable")))
  
